### ISSUE TITLE
Osheros spends too much time playing overwatch

### ISSUE THREAD

**Issue by Codadillo** [RoboticsTeam4904/2019-Code#23]
At face value this may seem like a meme issue, but I honestly consider you to use this as a starting point for productive discussion regarding this issue. Our leader, Osheros for those unsure, has been repeatedly leaving meetings early. This has been negatively impacting the health of this repository, as without our leader we are without guidance. Osheros is the most experienced member of the programming subteam, and therefore the best candidate for PR reviewing. Whenever he leaves, we have lost this vast power to harness. I think we need to start talking about possible solutions and innovations to correct this grievance.

**Comment by Krakavius** [comment]
I fully support this vote of no confidence in Osheros.

**Comment by NikhilSuresh24** [comment]
If you care about this, talk to Osher in person

**Comment by leijurv** [comment]
ok this is epic

**Comment by oshlern** [comment]
i quit :(

**Comment by billwpierce** [comment]
Stop.
